/// Flutter icons Heart
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Heart
///      fonts:
///       - asset: fonts/Heart.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';
import 'package:fluttericon/brandico_icons.dart';
import 'package:fluttericon/elusive_icons.dart';
import 'package:fluttericon/entypo_icons.dart';
import 'package:fluttericon/font_awesome5_icons.dart';
import 'package:fluttericon/font_awesome_icons.dart';
import 'package:fluttericon/fontelico_icons.dart';
import 'package:fluttericon/iconic_icons.dart';
import 'package:fluttericon/linearicons_free_icons.dart';
import 'package:fluttericon/linecons_icons.dart';
import 'package:fluttericon/maki_icons.dart';
import 'package:fluttericon/meteocons_icons.dart';
import 'package:fluttericon/mfg_labs_icons.dart';
import 'package:fluttericon/modern_pictograms_icons.dart';
import 'package:fluttericon/octicons_icons.dart';
import 'package:fluttericon/rpg_awesome_icons.dart';
import 'package:fluttericon/typicons_icons.dart';
import 'package:fluttericon/web_symbols_icons.dart';
import 'package:fluttericon/zocial_icons.dart';

class Heart {
  Heart._();

  static const _kFontFam = 'Heart';
  static const String? _kFontPkg = null;

  static const IconData heartbeat_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_pulse = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up = IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docs = IconData(0xf0c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xf21e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
